
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Precalculus'
tagline:          'from http://cnx.org/contents/fd53eae1-fa23-47c7-bb1b-972349835c3c@6.93 (CC-BY)'
url:              https://github.com/philschatz/precalculus-book
origin:           http://cnx.org/contents/fd53eae1-fa23-47c7-bb1b-972349835c3c@6.93

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          6.93

bookviewer:       http://philschatz.com/book-viewer

